name: Build

on:
  issues

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Install NPM dependencies
      run: npm install
    - name: Create README.md
      run: npm run start
      env:
        GITHUB_TOKEN: ${{ secrets.TOKEN }}
        GITHUB_REPOSITORY: ${{ github.repository }}
        SHOW_NUM: 8
    - name: Update README.md
      run: |-
        git diff
        git config --global user.email "issues-bot@test.com"
        git config --global user.name "Issues-bot"
        git add -A
        git commit -m "Updated README.md" || exit 0
        git push

